### ISSUE TITLE
Remove space when showWindowControls is false

### ISSUE THREAD

**Issue by outaTiME** [licatajustin/hyper-ayu#1] opened 2017-03-13 20:35 UTC
Hi pal, 

When using multiple tabs and the `showWindowControls` is false this plugin are using the windows control space, take a look de following capture, its possible or im doing something wrong, thanks and awesome work !!!

![screen_shot_2017-03-13_at_5_32_02_pm](https://cloud.githubusercontent.com/assets/140472/23874198/842cb64e-0813-11e7-86d1-0c2f90673124.png)

**Comment by outaTiME** [comment] 2017-03-13 20:37
Note: if use `hyper-tabs-enhanced` its works fine, take a look:

![screen shot 2017-03-13 at 5 36 53 pm](https://cloud.githubusercontent.com/assets/140472/23874285/c8ffebd8-0813-11e7-9151-95f68cdcc3fd.png)

**Comment by licatajustin** [comment] 2017-03-14 01:59
What Operating System are you using?

I'm trying to reproduce on Mac OS, but [it looks like this option is being ignored](https://github.com/zeit/hyper/issues/1164).

**Comment by outaTiME** [comment] 2017-03-14 02:05
Im running macos 10.12.3 (iMac 5k) with Hyper 1.3.1, here my settings:

Note: remove `hyper-tabs-enhanced` to reproduce the space.

```js
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 13,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',
    // fontFamily: 'Inconsolata-g',

    // terminal cursor background color (hex)
    cursorColor: '#F81CE5',

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // some color overrides. see http://bit.ly/29k1iU2 for
    // the full list
    colors: [
      '#000000',
      '#ff0000',
      '#33ff00',
      '#ffff00',
      '#0066ff',
      '#cc00ff',
      '#00ffff',
      '#d0d0d0',
      '#808080',
      '#ff0000',
      '#33ff00',
      '#ffff00',
      '#0066ff',
      '#cc00ff',
      '#00ffff',
      '#ffffff'
    ]
  },
  showWindowControls: false,
  hyperTabs: {
    // border: true,
    // trafficButtons: true
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hypersolar`
  //   `@company/project`
  //   `project#1.0.1`
  // "hyper-transparent-dynamic"
  plugins: ["hyper-font-smoothing", "hyper-tabs-enhanced", "hyper-statusline", "hyper-ayu"],

  // in development, you can create a directory under
  // `~/.hyperterm_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
```

**Comment by licatajustin** [comment] 2017-03-14 02:50
Thanks @outaTiME -- this should be fixed in [version 1.0.4](https://www.npmjs.com/package/hyper-ayu). I wasn't able to reproduce by setting `showWindowControls` in my `.hyper.js` configuration, but was able to by using some of the code in `hyper-tabs-enhanced`. I'm still curious how you were able to use `showWindowControls` since the option seems to be ignored by Hyper in Mac OS though 🤔

**Closed as completed by licatajustin** 2017-03-14 02:50 UTC

**Comment by outaTiME** [comment] 2017-03-14 03:36
mmm, something wired here ...
i update to version 1.0.4 but if i leave only `hyper-ayu` (without `hyper-tabs-enhaced`)  the `showWindowControls` is ignored.

**Comment by outaTiME** [comment] 2017-03-14 03:38
mmm, something wired here ...
i update to version 1.0.4 but if i leave only `hyper-ayu` (without `hyper-tabs-enhaced`)  the `showWindowControls` is ignored.

Note: without plugins the flag `showWindowControls` still ignored 😢

**Comment by outaTiME** [comment] 2017-03-14 03:41
Probably `hyper-tabs-enhaced` styles do the trick

**Comment by licatajustin** [comment] 2017-03-14 13:24
Yeah, it's supposed to be ignored on Mac OS, based on the link I sent in https://github.com/licatajustin/hyper-ayu/issues/1#issuecomment-286299108.
